#!/bin/bash

SELF=$(basename $0)

if [ $# -ne 1 ]
then
    echo "Not enough args"
    echo "    $SELF database"
    echo "    IE: $SELF build"
    exit 1
fi

DB=$1

if [ -d before ]
then
    if [ -d after ]
    then
        rm -r before
        mv after before
    fi
    DIR=after
else
  DIR=before
fi

mkdir $DIR

IFS="
"
if [ -e ~/scripts/tablelist.txt ]
then
    echo file
    TABLES=$(cat ~/scripts/tablelist.txt)
else
    echo database
    TABLES=$(psql vans -qc "\dt;" | cut -f2 -d\| | grep -v "\([0-9]\+\) rows")
fi

exit
for TABLE in $TABLES
do
    echo $TABLE
    pg_dump -d $DB -t $TABLE > $DIR/${TABLE}.sql
done
